# Generated by Django 5.1.7 on 2025-10-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='department',
            new_name='academic_de_name_67e679_idx',
            old_name='academic_de_name_0d11d1_idx',
        ),
        migrations.RenameIndex(
            model_name='departmentstaff',
            new_name='academic_de_departm_28e715_idx',
            old_name='academic_de_departm_9d4dc4_idx',
        ),
        migrations.RenameIndex(
            model_name='researchgroup',
            new_name='academic_re_name_bdc356_idx',
            old_name='academic_re_name_82c769_idx',
        ),
        migrations.RenameIndex(
            model_name='researchgroupmembership',
            new_name='academic_re_group_i_72c87b_idx',
            old_name='academic_re_group_i_2c3835_idx',
        ),
    ]
