# Generated by Django 5.1.7 on 2025-10-06 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="departmentinfo",
            name="department",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info",
                to="academic.department",
            ),
        ),
        migrations.AddField(
            model_name="departmentstaff",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to="academic.department",
            ),
        ),
        migrations.AddField(
            model_name="departmentstaff",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_staff_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="researchgroup",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="academic.department",
            ),
        ),
        migrations.AddField(
            model_name="researchgroup",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="researchgroupmembership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="academic.researchgroup",
            ),
        ),
        migrations.AddField(
            model_name="researchgroupmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["name"], name="academic_de_name_67e679_idx"),
        ),
        migrations.AddIndex(
            model_name="departmentstaff",
            index=models.Index(
                fields=["department", "user"], name="academic_de_departm_28e715_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="departmentstaff",
            unique_together={("department", "user")},
        ),
        migrations.AddIndex(
            model_name="researchgroup",
            index=models.Index(fields=["name"], name="academic_re_name_bdc356_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="researchgroup",
            unique_together={("department", "name")},
        ),
        migrations.AddIndex(
            model_name="researchgroupmembership",
            index=models.Index(
                fields=["group", "user"], name="academic_re_group_i_72c87b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="researchgroupmembership",
            unique_together={("group", "user")},
        ),
    ]
