# Generated by Django 5.1.7 on 2025-10-06 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0002_initial"),
        ("research", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="authors",
            field=models.ManyToManyField(
                related_name="articles", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="grouparticle",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_groups",
                to="research.article",
            ),
        ),
        migrations.AddField(
            model_name="grouparticle",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_articles",
                to="academic.researchgroup",
            ),
        ),
        migrations.AddField(
            model_name="groupproject",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="academic.researchgroup",
            ),
        ),
        migrations.AddField(
            model_name="groupproject",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["title"], name="research_ar_title_d1d6b8_idx"),
        ),
        migrations.AddIndex(
            model_name="grouparticle",
            index=models.Index(
                fields=["group", "article"], name="research_gr_group_i_2c291e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grouparticle",
            unique_together={("group", "article")},
        ),
        migrations.AddIndex(
            model_name="groupproject",
            index=models.Index(
                fields=["group", "status"], name="research_gr_group_i_6b152d_idx"
            ),
        ),
    ]
