# Generated by Django 5.1.7 on 2025-10-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_groupproject_extend"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("code", models.CharField(blank=True, max_length=64)),
                ("agency", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["title"], name="research_gr_title_f455c8_idx"),
                    models.Index(fields=["code"], name="research_gr_code_d53376_idx"),
                ],
            },
        ),
    ]
