# Generated by Django 5.1.7 on 2025-10-07 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0004_grant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="grant",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_grants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="grant",
            index=models.Index(
                fields=["leader"], name="research_gr_leader__2aee02_idx"
            ),
        ),
    ]
