# Generated by Django 5.1.7 on 2025-10-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.URLField(blank=True, help_text="URL до изображения аватара"),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Краткая биография / описание"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True, help_text="Должность / позиция пользователя", max_length=255
            ),
        ),
    ]
