# Generated by Django 5.1.7 on 2025-10-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_avatar_user_bio_user_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, help_text="Изображение аватара", upload_to="avatars/"
            ),
        ),
    ]
